# Generated by Django 4.1.5 on 2023-01-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderDetails",
            new_name="OrderDetail",
        ),
    ]
