# Generated by Django 4.1.5 on 2023-01-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_orderdetails_orderdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="birth_date",
            new_name="birthday",
        ),
    ]
