# Generated by Django 4.1.5 on 2023-02-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customuser_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(max_length=15)),
                (
                    "order_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.order"
                    ),
                ),
            ],
        ),
    ]
