# Generated by Django 4.1.5 on 2023-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_customuser_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_address",
            field=models.CharField(max_length=200),
        ),
    ]
