# Generated by Django 4.1.5 on 2023-02-10 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_orderdetail_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
