# Generated by Django 4.1.5 on 2023-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_orderdetail_quantity_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ManyToManyField(to="app.product"),
        ),
    ]
