# Generated by Django 4.1.5 on 2023-02-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_customer_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="total",
        ),
    ]
