# Generated by Django 4.1.5 on 2023-02-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_product_price_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
